apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgresql
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
        version: "{{ .Chart.AppVersion }}"
    spec:
      automountServiceAccountToken: false
      containers:
      - image: "{{ .Values.api.image.repository }}/postgresql:{{ .Chart.AppVersion }}"
        name: postgresql
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresql-pv
          subPath: postgresql
        - mountPath: /docker-entrypoint-initdb.d/initdb.sh
          name: postgresql-initdb
          subPath: initdb.sh
        env:
        - name: POSTGRES_DB
          value: devguard
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: db-secret
        - name: POSTGRES_USER
          value: devguard
        - name: KRATOS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: kratos-db-secret
        resources:
          limits:
            cpu: 4000m
            memory: 8024Mi
          requests:
            cpu: 1000m
            memory: 2056Mi
      restartPolicy: Always
      volumes:
      - name: postgresql-pv
        persistentVolumeClaim:
          claimName: postgresql-pvc
      - name: postgresql-initdb
        configMap:
          name: postgresql-initdb
