name: Naming Convention Policy Check
on: 
  pull_request:
      
jobs:
  documentation_check:
    uses: l3montree-dev/devguard-action/.github/workflows/naming-convention.yml@add-documentation-policy
    with:
      repositories: "l3montree-dev/devguard,l3montree-dev/devguard-documentation"
      ticket_repo: "l3montree-dev/devguard"